services:
  # Main API Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brand_detection_api
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - BUCKET_CROPS=${BUCKET_CROPS:-crops}
      - YOLO_MODEL_PATH=${MODEL_PATH:-models/best2.pt}
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
      - ./tmp:/app/tmp
    restart: unless-stopped

  # Streamlit Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: brand_detection_frontend
    environment:
      - API_BASE_URL=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api
    restart: unless-stopped

networks:
  default:
    driver: bridge
