project:
  name: "brand-detection-cv"
  version: "1.0.0"
  description: "Computer Vision model for brand detection in videos"

data:
  raw_images_path: "data/raw/images"
  raw_videos_path: "data/raw/videos"
  processed_path: "data/processed"
  annotations_path: "data/processed/annotations"
  dataset_split:
    train: 0.7
    val: 0.2
    test: 0.1

model:
  architecture: "yolov8"  # Options: yolov8, faster_rcnn, ssd
  pretrained: true
  input_size: [640, 640]
  confidence_threshold: 0.5
  iou_threshold: 0.4
  
training:
  batch_size: 16
  epochs: 100
  learning_rate: 0.001
  optimizer: "adam"
  scheduler: "cosine"
  early_stopping_patience: 10
  save_best_only: true

augmentation:
  enable: true
  horizontal_flip: 0.5
  vertical_flip: 0.1
  rotation: 15
  brightness: 0.2
  contrast: 0.2
  saturation: 0.2
  hue: 0.1

video_processing:
  fps_sample: 1  # Process 1 frame per second
  output_format: "mp4"
  save_annotated: true

database:
  type: "postgresql"  # Options: postgresql, sqlite
  host: "localhost"
  port: 5432
  name: "brand_detection"
  user: "postgres"
  password: ""

api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  max_video_size_mb: 100

brands:
  - name: "coca_cola"
    id: 0
    color: [255, 0, 0]
  - name: "pepsi"
    id: 1
    color: [0, 0, 255]
  - name: "nike"
    id: 2
    color: [0, 255, 0]
  - name: "adidas"
    id: 3
    color: [255, 255, 0]

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"
